const invoices = [
  {
    id: "RS3465",
    adress: "Bahçelievler Mh. 14.Sk.",
    city: "Ankara",
    postCode: 34090,
    country: "Turkey",
    clientName: "Fatih",
    clientEmail: "fatih@gmail.com",
    clientAdress: "Emek Mh. 20 Sk.",
    clientCity: "Ankara",
    clientPostCode: 34050,
    clientCountry: "Turkey",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: 14,
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
      {
        name: "Website Design",
        quantity: 1,
        price: 2600,
        total: 2600,
      },
    ],
    totalPrice: 6200,
    status: "draft",
  },
  {
    id: "QR3571",
    adress: "Bahçelievler Mh. 14.Sk.",
    city: "Ankara",
    postCode: 34090,
    country: "Turkey",
    clientName: "John",
    clientEmail: "john@gmail.com",
    clientAdress: "Emek Mh. 20 Sk.",
    clientCity: "Ankara",
    clientPostCode: 34050,
    clientCountry: "Turkey",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-14",
    paymentTerm: 7,
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
    ],
    totalPrice: 6200,
    status: "pending",
  },
  {
    id: "ZR4290",
    adress: "Bahçelievler Mh. 14.Sk.",
    city: "Ankara",
    postCode: 34090,
    country: "Turkey",
    clientName: "Jane",
    clientEmail: "jane@gmail.com",
    clientAdress: "Emek Mh. 20 Sk.",
    clientCity: "Ankara",
    clientPostCode: 34050,
    clientCountry: "Turkey",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: 14,
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
      {
        name: "Website Design",
        quantity: 1,
        price: 2600,
        total: 2600,
      },
    ],
    totalPrice: 6200,
    status: "paid",
  },
  {
    id: "AL7190",
    adress: "Bahçelievler Mh. 14.Sk.",
    city: "Ankara",
    postCode: 34090,
    country: "Turkey",
    clientName: "Fred",
    clientEmail: "fred@gmail.com",
    clientAdress: "Hackney 198.St.",
    clientCity: "London",
    clientPostCode: 54632,
    clientCountry: "UK",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: 14,
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
      {
        name: "Website Design",
        quantity: 1,
        price: 2600,
        total: 2600,
      },
    ],
    totalPrice: 6200,
    status: "paid",
  },
  {
    id: "RM8805",
    adress: "Bahçelievler Mh. 14.Sk.",
    city: "Ankara",
    postCode: 34090,
    country: "Turkey",
    clientName: "Jennifer",
    clientEmail: "jennifer@gmail.com",
    clientAdress: "Emek Mh. 20 Sk.",
    clientCity: "Ankara",
    clientPostCode: 34050,
    clientCountry: "Turkey",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: 14,
    projectDesc: "Brand Creation",
    projects: [
      {
        name: "Advertisement",
        quantity: 2,
        price: 1900,
        total: 3800,
      },
      {
        name: "Google Ads",
        quantity: 1,
        price: 2000,
        total: 2000,
      },
    ],
    totalPrice: 5800,
    status: "pending",
  },
];

export default invoices;
